version: "1"

host: "localhost"

API:
  net:
    protocol: "https"
    port: "8000"
  zip:
    enabled: true
    min_size: 1000
  cors:
    enabled: true
    origins:
      - "*"
    methods:
      - "*"

APIWS:
  net:
    protocol: "ws"
    port: "8100"

CryptoAPI:
  net:
    protocol: "http"
    port: "8200"
  zip:
    enabled: true
    min_size: 1000
  cors:
    enabled: true
    origins:
      - "*"
    methods:
      - "*"
  graphic_card: "gt-710"

StatusAPI:
  net:
    protocol: "http"
    port: "8300"
  cors:
    enabled: true
    origins:
      - "*"
    methods:
      - "*"
