version: "3"

services:

  backend:
    build:
      context: .
      dockerfile: Dockerfile.fastapi
    container_name: fastapi_backend
    ports:
      - "8000:8000"
    depends_on:
      - database

  database:
    ports:
      - '27018:27018'
    container_name: mongodb_database
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongoadmin
      - MONGO_INITDB_ROOT_PASSWORD=bdung
    image: mongo
    volumes:
      - mongodb_persistant_data:/data/db


volumes:
  mongodb_persistant_data:
    driver: local