version: "3"

services:

  fastapi:
    build:
      context: .
      dockerfile: Dockerfile.fastapi
    container_name: fastapi_backend
    ports:
      - "8000:8000"
    depends_on:
      - database


volumes:
  mongodb_persistant_data:
    driver: local