version: "3"

services:

  database:
    
    image: mongo
    deploy:
      mode: global
      update_config:
        parallelism: 2
        delay: 10s
        failure_action: rollback
        monitor: 10s
        max_failure_ratio: 0.5
        order: stop-first
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s
    ports:
      - '27018:27018'
    container_name: mongodb_database
    restart: always
    command: mongod --port 27018
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongoadmin
      - MONGO_INITDB_ROOT_PASSWORD=bdung
    volumes:
      - type: bind
        source: /home/vagrant/data/db  # Ruta del directorio en el sistema de archivos del host
        target: /data/db   # Ruta dentro del contenedor
    healthcheck:
      test: ["CMD-SHELL", "mongo --eval 'db.stats()'"] # Comprueba que la base de datos responde correctamente
      interval: 10s
      retries: 5
      start_period: 30s

