apiVersion: v1
kind: Service
metadata:
  name: mongodb
spec:
  selector:
    app: mongodb
  ports:
    - protocol: TCP
      port: 30000  # MongoDB usa el puerto 27017 por defecto
      targetPort: 27017
